{% set name = "vclean" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/2d/eb/83658c7ed297aaba3fbef1a6da587f4b3d15875d7571b468b97466e216ba/vclean-0.1.4.tar.gz
  sha256: 1b2348a170958bc191e1bd9bfa3ce4e29b95c2d038d8950a3f85865428058b0b

build:
  entry_points:
    - vclean = vclean.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage("vclean", max_pin="x") }}

requirements:
  host:
    - python ==3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python ==3.9
    - pandas
    - numpy
    - matplotlib-base
    - seaborn
    - scikit-learn
    - lightgbm
    - biopython
    - checkv
    - seqkit
    - kmer-jellyfish
    - prodigal
    - mmseqs2

test:
  commands:
    - vclean --help

about:
  summary: 'vClean: Assessing the contamination of viral genomes'
  home: https://github.com/TsumaR/vclean
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TsumaR
