{% set name = "vclean" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fb/4a/498e3c044ec4df7c331a892e31a42aeb6f2b1c1500bc76aab9dc6365e9e0/vclean-0.1.1.tar.gz
  sha256: fda74c01c9f2bb789f1c5bff0f5e6095411b6896d3538b4ca9b894fe412e4dd3

build:
  entry_points:
    - vclean = vclean.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage("vclean", max_pin="x") }}

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - pandas
    - numpy
    - matplotlib-base
    - seaborn
    - scikit-learn
    - lightgbm
    - biopython
    - checkv
    - seqkit
    - kmer-jellyfish
    - prodigal
    - mmseqs2

test:
  commands:
    - vclean --help

about:
  summary: 'vClean: Assessing the contamination of viral genomes'
  home: https://github.com/TsumaR/vclean
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TsumaR
